name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ lcov libcurl4-openssl-dev

    - name: Create build directory
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build

    - name: Run tests
      run: cd build && ctest --output-on-failure
